/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#304671",
        "surface-dim": "#131313",
        "surface-container-high": "#2a2a2a",
        "outline-variant": "#4e4639",
        "inverse-primary": "#775a19",
        "primary-container": "#c5a059",
        "on-secondary-container": "#342800",
        "on-secondary-fixed-variant": "#574500",
        "surface-container": "#201f1f",
        "on-tertiary-fixed": "#001a41",
        "on-surface-variant": "#d1c5b4",
        "tertiary-container": "#8fa5d6",
        "secondary-fixed": "#ffe088",
        "surface-tint": "#e9c176",
        "on-secondary": "#3c2f00",
        "on-primary-fixed-variant": "#5d4201",
        "surface-container-low": "#1c1b1b",
        secondary: "#e9c349",
        outline: "#9a8f80",
        "on-error": "#690005",
        background: "#131313",
        "primary-fixed": "#ffdea5",
        "on-primary-fixed": "#261900",
        "tertiary-fixed": "#d8e2ff",
        "on-surface": "#e5e2e1",
        "surface-bright": "#393939",
        primary: "#e9c176",
        "on-tertiary": "#173059",
        "on-primary-container": "#4e3700",
        "primary-fixed-dim": "#e9c176",
        "on-tertiary-container": "#233a65",
        "on-primary": "#412d00",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        tertiary: "#b0c6f9",
        error: "#ffb4ab",
        surface: "#131313",
        "secondary-container": "#af8d11",
        "error-container": "#93000a",
        "inverse-on-surface": "#313030",
        "on-background": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#b0c6f9",
        "secondary-fixed-dim": "#e9c349",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
